// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiEa77aWSbzHYiIGDm8pzF-YdfBcpVOMw',
    appId: '1:217255121161:web:45f27722d3659d922c03d8',
    messagingSenderId: '217255121161',
    projectId: 'shopping-gg-2027',
    authDomain: 'shopping-gg-2027.firebaseapp.com',
    storageBucket: 'shopping-gg-2027.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmsYsoYXkehXqITKmV6AKXBNPx-flpF-A',
    appId: '1:217255121161:android:fcb086dbefcb57e32c03d8',
    messagingSenderId: '217255121161',
    projectId: 'shopping-gg-2027',
    storageBucket: 'shopping-gg-2027.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmBY_GnRKLyiM2SIJ3Q84U5wtWY7E8XSg',
    appId: '1:217255121161:ios:fdeb39a72d8fbefb2c03d8',
    messagingSenderId: '217255121161',
    projectId: 'shopping-gg-2027',
    storageBucket: 'shopping-gg-2027.firebasestorage.app',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmBY_GnRKLyiM2SIJ3Q84U5wtWY7E8XSg',
    appId: '1:217255121161:ios:fdeb39a72d8fbefb2c03d8',
    messagingSenderId: '217255121161',
    projectId: 'shopping-gg-2027',
    storageBucket: 'shopping-gg-2027.firebasestorage.app',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiEa77aWSbzHYiIGDm8pzF-YdfBcpVOMw',
    appId: '1:217255121161:web:172f5132b67e95ed2c03d8',
    messagingSenderId: '217255121161',
    projectId: 'shopping-gg-2027',
    authDomain: 'shopping-gg-2027.firebaseapp.com',
    storageBucket: 'shopping-gg-2027.firebasestorage.app',
  );
}
