class S {
  static const Map<String, Map<String, String>> _translations = {
    // App Bar & Welcome
    'app_name': {
      'ar': 'سوقنا المحلي',
      'en': 'Our Local Market',
      'de': 'Unser Lokaler Markt',
      'zh': '我们的本地市场',
      'ru': 'Наш Местный Рынок',
      'fr': 'Notre Marché Local',
    },
    'buy': {
      'ar': 'شراء',
      'en': 'Buy',
      'de': 'Kaufen',
      'zh': '购买',
      'ru': 'Купить',
      'fr': 'Acheter',
    },
    'enter_phone_error': {
      'ar': 'من فضلك أدخل رقم الهاتف',
      'en': 'Please enter phone number',
      'de': 'Bitte geben Sie eine Telefonnummer ein',
      'zh': '请输入电话号码',
      'ru': 'Пожалуйста, введите номер телефона',
      'fr': 'Veuillez saisir le numéro de téléphone',
    },
    'invalid_phone_error': {
      'ar': 'رقم الهاتف غير صحيح',
      'en': 'Invalid phone number',
      'de': 'Ungültige Telefonnummer',
      'zh': '电话号码无效',
      'ru': 'Неверный номер телефона',
      'fr': 'Numéro de téléphone invalide',
    },
    'numbers_only_error': {
      'ar': 'يجب إدخال أرقام فقط',
      'en': 'Must contain numbers only',
      'de': 'Darf nur Zahlen enthalten',
      'zh': '只能包含数字',
      'ru': 'Должно содержать только цифры',
      'fr': 'Doit contenir uniquement des chiffres',
    },
    // Navigation
    'home': {
      'ar': 'الرئيسية',
      'en': 'Home',
      'de': 'Startseite',
      'zh': '首页',
      'ru': 'Главная',
      'fr': 'Accueil',
    },
    'account': {
      'ar': 'الحساب',
      'en': 'Account',
      'de': 'Konto',
      'zh': '账户',
      'ru': 'Аккаунт',
      'fr': 'Compte',
    },
    'cart': {
      'ar': 'العربة',
      'en': 'Cart',
      'de': 'Warenkorb',
      'zh': '购物车',
      'ru': 'Корзина',
      'fr': 'Panier',
    },
    // HomeScreen
    'search_hint': {
      'ar': 'بتدور على إيه؟',
      'en': 'What are you looking for?',
      'de': 'Wonach suchen Sie?',
      'zh': '你在找什么？',
      'ru': 'Что вы ищете?',
      'fr': 'Que cherchez-vous ?',
    },
    'weekend_offers': {
      'ar': 'عروض نهاية الأسبوع!',
      'en': 'Weekend Offers!',
      'de': 'Wochenendangebote!',
      'zh': '周末特惠！',
      'ru': 'Предложения на выходные!',
      'fr': 'Offres du week-end !',
    },
    'discounts_50': {
      'ar': 'خصومات تصل إلى 50%',
      'en': 'Discounts up to 50%',
      'de': 'Rabatte bis zu 50%',
      'zh': '折扣高达 50%',
      'ru': 'Скидки до 50%',
      'fr': 'Remises jusqu\'à 50%',
    },
    'categories': {
      'ar': 'الأقسام',
      'en': 'Categories',
      'de': 'Kategorien',
      'zh': '类别',
      'ru': 'Категории',
      'fr': 'Catégories',
    },
    'best_sellers': {
      'ar': 'الأكثر مبيعاً 🔥',
      'en': 'Best Sellers 🔥',
      'de': 'Bestseller 🔥',
      'zh': '热销商品 🔥',
      'ru': 'Хиты продаж 🔥',
      'fr': 'Meilleures ventes 🔥',
    },
    'no_products': {
      'ar': 'لا توجد منتجات تطابق البحث!',
      'en': 'No products match your search!',
      'de': 'Keine Produkte entsprechen Ihrer Suche!',
      'zh': '没有找到符合搜索条件的产品！',
      'ru': 'Нет товаров, соответствующих поиску!',
      'fr': 'Aucun produit ne correspond à votre recherche !',
    },
    'add_to_cart_msg': {
      'ar': 'تمت إضافة المنتج للعربة',
      'en': 'Product added to cart',
      'de': 'Produkt zum Warenkorb hinzugefügt',
      'zh': '产品已添加到购物车',
      'ru': 'Товар добавлен в корзину',
      'fr': 'Produit ajouté au panier',
    },
    'currency': {
      'ar': 'ج.م',
      'en': 'EGP',
      'de': 'EGP',
      'zh': 'EGP',
      'ru': 'EGP',
      'fr': 'EGP',
    },
    // CartScreen
    'empty_cart': {
      'ar': 'عربة التسوق فاضية!',
      'en': 'Your cart is empty!',
      'de': 'Ihr Warenkorb ist leer!',
      'zh': '您的购物车是空的！',
      'ru': 'Ваша корзина пуста!',
      'fr': 'Votre panier est vide !',
    },
    'total_price': {
      'ar': 'إجمالي الحساب:',
      'en': 'Total Price:',
      'de': 'Gesamtpreis:',
      'zh': '总价：',
      'ru': 'Общая стоимость:',
      'fr': 'Prix total :',
    },
    'proceed_to_checkout': {
      'ar': 'إتمام عملية الشراء',
      'en': 'Proceed to Checkout',
      'de': 'Zur Kasse gehen',
      'zh': '去结算',
      'ru': 'Перейти к оформлению',
      'fr': 'Passer à la caisse',
    },
    // CheckoutScreen
    'checkout': {
      'ar': 'الدفع والشحن',
      'en': 'Checkout',
      'de': 'Auschecken',
      'zh': '结算',
      'ru': 'Оформление заказа',
      'fr': 'Paiement',
    },
    'shipping_address': {
      'ar': 'العنوان بالتفصيل',
      'en': 'Detailed Shipping Address',
      'de': 'Detaillierte Lieferadresse',
      'zh': '详细收货地址',
      'ru': 'Подробный адрес доставки',
      'fr': 'Adresse de livraison détaillée',
    },
    'enter_address_error': {
      'ar': 'من فضلك أدخل العنوان بالتفصيل',
      'en': 'Please enter shipping address',
      'de': 'Bitte geben Sie die Lieferadresse ein',
      'zh': '请输入收货地址',
      'ru': 'Пожалуйста, введите адрес доставки',
      'fr': 'Veuillez saisir l\'adresse de livraison',
    },
    'phone_number_label': {
      'ar': 'رقم الهاتف للتواصل',
      'en': 'Phone Number for Contact',
      'de': 'Telefonnummer für Kontakt',
      'zh': '联系电话',
      'ru': 'Номер телефона для связи',
      'fr': 'Numéro de téléphone de contact',
    },
    'recipient_name': {
      'ar': 'اسم المستلم',
      'en': 'Recipient Name',
      'de': 'Empfängername',
      'zh': '收件人姓名',
      'ru': 'Имя получателя',
      'fr': 'Nom du destinataire',
    },
    'enter_recipient_name': {
      'ar': 'من فضلك أدخل اسم المستلم',
      'en': 'Please enter recipient name',
      'de': 'Bitte geben Sie den Empfängernamen ein',
      'zh': '请输入收件人姓名',
      'ru': 'Пожалуйста, введите имя получателя',
      'fr': 'Veuillez saisir le nom du destinataire',
    },
    'order_summary': {
      'ar': 'ملخص الطلب',
      'en': 'Order Summary',
      'de': 'Bestellübersicht',
      'zh': '订单总结',
      'ru': 'Детали заказа',
      'fr': 'Résumé de la commande',
    },
    'shipping_fee': {
      'ar': 'رسوم الشحن:',
      'en': 'Shipping Fee:',
      'de': 'Versandkosten:',
      'zh': '运费：',
      'ru': 'Стоимость доставки:',
      'fr': 'Frais de livraison :',
    },
    'total_amount': {
      'ar': 'المبلغ الإجمالي:',
      'en': 'Total Amount:',
      'de': 'Gesamtbetrag:',
      'zh': '总金额：',
      'ru': 'Итоговая сумма:',
      'fr': 'Montant total :',
    },
    'cash_on_delivery': {
      'ar': 'الدفع عند الاستلام',
      'en': 'Cash on Delivery',
      'de': 'Nachnahme',
      'zh': '货到付款',
      'ru': 'Оплата при получении',
      'fr': 'Paiement à la livraison',
    },
    'confirm_order': {
      'ar': 'تأكيد الطلب وشحن المنتجات',
      'en': 'Confirm Order & Ship',
      'de': 'Bestellung bestätigen & versenden',
      'zh': '确认订单并出货',
      'ru': 'Подтвердить заказ и отправить',
      'fr': 'Confirmer la commande',
    },
    'order_success': {
      'ar': 'تم تسجيل طلبك بنجاح! 🎉',
      'en': 'Order placed successfully! 🎉',
      'de': 'Bestellung erfolgreich aufgegeben! 🎉',
      'zh': '订单提交成功！🎉',
      'ru': 'Заказ успешно оформлен! 🎉',
      'fr': 'Commande passée avec succès ! 🎉',
    },
    'empty_order_warning': {
      'ar': 'العربة فارغة!',
      'en': 'Cart is empty!',
      'de': 'Warenkorb ist leer!',
      'zh': '购物车是空的！',
      'ru': 'Корзина пуста!',
      'fr': 'Le panier est vide !',
    },
    // ProfileScreen
    'customer': {
      'ar': 'عميل',
      'en': 'Customer',
      'de': 'Kunde',
      'zh': '客户',
      'ru': 'Покупатель',
      'fr': 'Client',
    },
    'local_seller': {
      'ar': 'بائع محلي',
      'en': 'Local Seller',
      'de': 'Lokaler Verkäufer',
      'zh': '本地商家',
      'ru': 'Местный Продавец',
      'fr': 'Vendeur Local',
    },
    'delivery_driver': {
      'ar': 'مندوب توصيل',
      'en': 'Delivery Driver',
      'de': 'Zusteller',
      'zh': '配送员',
      'ru': 'Курьер',
      'fr': 'Livreur',
    },
    'edit_profile': {
      'ar': 'تعديل الحساب',
      'en': 'Edit Profile',
      'de': 'Profil bearbeiten',
      'zh': '编辑个人资料',
      'ru': 'Редактировать профиль',
      'fr': 'Modifier le profil',
    },
    'my_orders': {
      'ar': 'طلباتي السابقة',
      'en': 'My Orders',
      'de': 'Meine Bestellungen',
      'zh': '我的订单',
      'ru': 'Мои заказы',
      'fr': 'Mes commandes',
    },
    'shipping_addresses': {
      'ar': 'عناوين الشحن',
      'en': 'Shipping Addresses',
      'de': 'Lieferadressen',
      'zh': '收货地址',
      'ru': 'Адреса доставки',
      'fr': 'Adresses de livraison',
    },
    'help_center': {
      'ar': 'مركز المساعدة',
      'en': 'Help Center',
      'de': 'Hilfezentrum',
      'zh': '帮助中心',
      'ru': 'Справочный центр',
      'fr': 'Centre d\'aide',
    },
    'change_language': {
      'ar': 'تغيير اللغة',
      'en': 'Change Language',
      'de': 'Sprache ändern',
      'zh': '更改语言',
      'ru': 'Сменить язык',
      'fr': 'Changer de langue',
    },
    'join_partner': {
      'ar': 'انضم إلينا كشريك',
      'en': 'Join us as a partner',
      'de': 'Werden Sie Partner',
      'zh': '加入我们成为合作伙伴',
      'ru': 'Присоединяйтесь к нам',
      'fr': 'Devenir partenaire',
    },
    'register_seller': {
      'ar': 'التسجيل كبائع',
      'en': 'Register as Seller',
      'de': 'Als Verkäufer registrieren',
      'zh': '注册为商家',
      'ru': 'Регистрация продавца',
      'fr': 'S\'enregistrer comme vendeur',
    },
    'register_delivery': {
      'ar': 'التسجيل كدليفري',
      'en': 'Register as Delivery',
      'de': 'Als Zusteller registrieren',
      'zh': '注册为配送员',
      'ru': 'Регистрация курьера',
      'fr': 'S\'enregistrer comme livreur',
    },
    'seller_dashboard': {
      'ar': 'لوحة تحكم البائع',
      'en': 'Seller Dashboard',
      'de': 'Verkäufer-Dashboard',
      'zh': '商家控制台',
      'ru': 'Панель продавца',
      'fr': 'Tableau de bord vendeur',
    },
    'delivery_dashboard': {
      'ar': 'لوحة تحكم الدليفري',
      'en': 'Delivery Dashboard',
      'de': 'Zusteller-Dashboard',
      'zh': '配送员控制台',
      'ru': 'Панель курьера',
      'fr': 'Tableau de bord livreur',
    },
    'reset_customer': {
      'ar': 'الرجوع لحساب العميل',
      'en': 'Reset to Customer Account',
      'de': 'Zum Kundenkonto zurückkehren',
      'zh': '切回客户账号',
      'ru': 'Вернуться к аккаунту клиента',
      'fr': 'Retour au compte client',
    },
    'logout': {
      'ar': 'تسجيل الخروج',
      'en': 'Log Out',
      'de': 'Abmelden',
      'zh': '退出登录',
      'ru': 'Выйти из системы',
      'fr': 'Se déconnecter',
    },
    'default_address_msg': {
      'ar': 'عنوان الشحن الافتراضي: القاهرة، مصر',
      'en': 'Default Address: Cairo, Egypt',
      'de': 'Standardadresse: Kairo, Ägypten',
      'zh': '默认地址：埃及开罗',
      'ru': 'Адрес по умолчанию: Каир, Египет',
      'fr': 'Adresse par défaut : Le Caire, Égypte',
    },
    'help_dialog_content': {
      'ar': 'للدعم الفني، يرجى التواصل على البريد الإلكتروني support@example.com',
      'en': 'For support, please contact us at support@example.com',
      'de': 'Für Support kontaktieren Sie uns unter support@example.com',
      'zh': '如需技术支持，请联系 support@example.com',
      'ru': 'Для поддержки свяжитесь с нами по электронной почте support@example.com',
      'fr': 'Pour toute assistance, contactez-nous à support@example.com',
    },
    'close': {
      'ar': 'إغلاق',
      'en': 'Close',
      'de': 'Schließen',
      'zh': '关闭',
      'ru': 'Закрыть',
      'fr': 'Fermer',
    },
    'logout_confirm_body': {
      'ar': 'هل أنت متأكد من رغبتك في تسجيل الخروج؟',
      'en': 'Are you sure you want to log out?',
      'de': 'Sind Sie sicher, dass Sie sich abmelden möchten?',
      'zh': '你确定要退出登录吗？',
      'ru': 'Вы уверены, что хотите выйти?',
      'fr': 'Êtes-vous sûr de vouloir vous déconnecter ?',
    },
    'cancel': {
      'ar': 'إلغاء',
      'en': 'Cancel',
      'de': 'Abbrechen',
      'zh': '取消',
      'ru': 'Отмена',
      'fr': 'Annuler',
    },
    'exit': {
      'ar': 'خروج',
      'en': 'Exit',
      'de': 'Verlassen',
      'zh': '退出',
      'ru': 'Выйти',
      'fr': 'Quitter',
    },
    'logout_success': {
      'ar': 'تم تسجيل الخروج بنجاح',
      'en': 'Logged out successfully',
      'de': 'Erfolgreich abgemeldet',
      'zh': '成功退出登录',
      'ru': 'Выход выполнен успешно',
      'fr': 'Déconnexion réussie',
    },
    // EditProfileScreen
    'edit_profile_title': {
      'ar': 'تعديل الملف الشخصي',
      'en': 'Edit Profile',
      'de': 'Profil Bearbeiten',
      'zh': '编辑个人资料',
      'ru': 'Редактировать профиль',
      'fr': 'Modifier le profil',
    },
    'full_name': {
      'ar': 'الاسم بالكامل',
      'en': 'Full Name',
      'de': 'Vollständiger Name',
      'zh': '姓名',
      'ru': 'Полное имя',
      'fr': 'Nom complet',
    },
    'email_address': {
      'ar': 'البريد الإلكتروني',
      'en': 'Email Address',
      'de': 'E-Mail-Adresse',
      'zh': '电子邮件',
      'ru': 'Электронная почта',
      'fr': 'Adresse e-mail',
    },
    'phone_number': {
      'ar': 'رقم الهاتف',
      'en': 'Phone Number',
      'de': 'Telefonnummer',
      'zh': '电话号码',
      'ru': 'Номер телефона',
      'fr': 'Numéro de téléphone',
    },
    'save_changes': {
      'ar': 'حفظ التعديلات',
      'en': 'Save Changes',
      'de': 'Änderungen speichern',
      'zh': '保存修改',
      'ru': 'Сохранить изменения',
      'fr': 'Enregistrer les modifications',
    },
    'profile_updated': {
      'ar': 'تم تحديث البيانات بنجاح! 🎉',
      'en': 'Profile updated successfully! 🎉',
      'de': 'Profil erfolgreich aktualisiert! 🎉',
      'zh': '个人资料更新成功！🎉',
      'ru': 'Профиль успешно обновлен! 🎉',
      'fr': 'Profil mis à jour avec succès ! 🎉',
    },
    'enter_name_error': {
      'ar': 'من فضلك أدخل الاسم',
      'en': 'Please enter your name',
      'de': 'Bitte geben Sie Ihren Namen ein',
      'zh': '请输入您的姓名',
      'ru': 'Пожалуйста, введите ваше имя',
      'fr': 'Veuillez saisir votre nom',
    },
    'enter_email_error': {
      'ar': 'من فضلك أدخل البريد الإلكتروني',
      'en': 'Please enter your email',
      'de': 'Bitte geben Sie Ihre E-Mail ein',
      'zh': '请输入您的电子邮件',
      'ru': 'Пожалуйста, введите ваш email',
      'fr': 'Veuillez saisir votre e-mail',
    },
    'invalid_email_error': {
      'ar': 'البريد الإلكتروني غير صحيح',
      'en': 'Invalid email address',
      'de': 'Ungültige E-Mail-Adresse',
      'zh': '电子邮件地址无效',
      'ru': 'Неверный адрес электронной почты',
      'fr': 'Adresse e-mail invalide',
    },
    // MyOrdersScreen
    'no_previous_orders': {
      'ar': 'لا توجد طلبات سابقة حالياً!',
      'en': 'No previous orders found!',
      'de': 'Keine vorherigen Bestellungen gefunden!',
      'zh': '暂无历史订单！',
      'ru': 'Предыдущих заказов не найдено!',
      'fr': 'Aucune commande précédente trouvée !',
    },
    'order_id': {
      'ar': 'طلب رقم:',
      'en': 'Order ID:',
      'de': 'Bestell-ID:',
      'zh': '订单号：',
      'ru': 'Заказ №:',
      'fr': 'ID Commande :',
    },
    'order_date': {
      'ar': 'تاريخ الطلب:',
      'en': 'Date:',
      'de': 'Datum:',
      'zh': '日期：',
      'ru': 'Дата:',
      'fr': 'Date :',
    },
    'order_status': {
      'ar': 'حالة الطلب:',
      'en': 'Status:',
      'de': 'Status:',
      'zh': '状态：',
      'ru': 'Статус:',
      'fr': 'Statut :',
    },
    'status_pending': {
      'ar': 'قيد المراجعة',
      'en': 'Pending',
      'de': 'Ausstehend',
      'zh': '待处理',
      'ru': 'В ожидании',
      'fr': 'En attente',
    },
    'status_delivered': {
      'ar': 'تم التوصيل',
      'en': 'Delivered',
      'de': 'Geliefert',
      'zh': '已送达',
      'ru': 'Доставлен',
      'fr': 'Livré',
    },
    'status_shipping': {
      'ar': 'جاري الشحن',
      'en': 'Shipping',
      'de': 'Im Versand',
      'zh': '配送中',
      'ru': 'Доставляется',
      'fr': 'En cours de livraison',
    },
    'items_label': {
      'ar': 'المنتجات:',
      'en': 'Items:',
      'de': 'Artikel:',
      'zh': '商品：',
      'ru': 'Товары:',
      'fr': 'Articles :',
    },
    'qty_label': {
      'ar': 'الكمية:',
      'en': 'Qty:',
      'de': 'Menge:',
      'zh': '数量：',
      'ru': 'Кол-во:',
      'fr': 'Qté :',
    },
    // ProductDetailsScreen
    'seller_label': {
      'ar': 'البائع:',
      'en': 'Seller:',
      'de': 'Verkäufer:',
      'zh': '商家：',
      'ru': 'Продавец:',
      'fr': 'Vendeur :',
    },
    'category_label': {
      'ar': 'القسم:',
      'en': 'Category:',
      'de': 'Kategorie:',
      'zh': '类别：',
      'ru': 'Категория:',
      'fr': 'Catégorie :',
    },
    'product_description': {
      'ar': 'وصف المنتج',
      'en': 'Product Description',
      'de': 'Produktbeschreibung',
      'zh': '产品描述',
      'ru': 'Описание товара',
      'fr': 'Description du produit',
    },
    'dummy_description': {
      'ar': 'هذا المنتج مصنوع من أجود الخامات المحلية لضمان جودة عالية ودعم الصناعة الوطنية.',
      'en': 'This product is made from the finest local materials to ensure high quality and support local industry.',
      'de': 'Dieses Produkt wird aus feinsten lokalen Materialien hergestellt, um eine hohe Qualität zu gewährleisten und die lokale Industrie zu unterstützen.',
      'zh': '本产品采用优质本地材料制成，确保高品质并支持本地产业。',
      'ru': 'Этот продукт изготовлен из лучших местных материалов, чтобы гарантировать высокое качество и поддерживать отечественного производителя.',
      'fr': 'Ce produit est fabriqué à partir des meilleurs matériaux locaux afin de garantir une qualité supérieure et de soutenir l\'industrie locale.',
    },
    'add_to_cart_btn': {
      'ar': 'إضافة إلى العربة',
      'en': 'Add to Cart',
      'de': 'In den Warenkorb',
      'zh': '加入购物车',
      'ru': 'Добавить в корзину',
      'fr': 'Ajouter au panier',
    },
    // AddProductScreen
    'add_product_title': {
      'ar': 'إضافة منتج جديد',
      'en': 'Add New Product',
      'de': 'Neues Produkt hinzufügen',
      'zh': '添加新产品',
      'ru': 'Добавить новый товар',
      'fr': 'Ajouter un nouveau produit',
    },
    'product_name_ar': {
      'ar': 'اسم المنتج (بالعربية)',
      'en': 'Product Name (Arabic)',
      'de': 'Produktname (Arabisch)',
      'zh': '商品名称（阿拉伯语）',
      'ru': 'Название товара (на арабском)',
      'fr': 'Nom du produit (arabe)',
    },
    'product_name_en': {
      'ar': 'اسم المنتج (بالإنجليزية)',
      'en': 'Product Name (English)',
      'de': 'Produktname (Englisch)',
      'zh': '商品名称（英语）',
      'ru': 'Название товара (на английском)',
      'fr': 'Nom du produit (anglais)',
    },
    'product_price': {
      'ar': 'سعر المنتج',
      'en': 'Product Price',
      'de': 'Produktpreis',
      'zh': '商品价格',
      'ru': 'Цена товара',
      'fr': 'Prix du produit',
    },
    'product_category': {
      'ar': 'قسم المنتج',
      'en': 'Product Category',
      'de': 'Produktkategorie',
      'zh': '商品类别',
      'ru': 'Категория товара',
      'fr': 'Catégorie du produit',
    },
    'image_url_optional': {
      'ar': 'رابط صورة المنتج (اختياري)',
      'en': 'Product Image URL (Optional)',
      'de': 'Produktbild-URL (Optional)',
      'zh': '商品图片链接（可选）',
      'ru': 'Ссылка на изображение товара (необязательно)',
      'fr': 'URL de l\'image du produit (optionnel)',
    },
    'add_product_btn': {
      'ar': 'إضافة المنتج للمتجر',
      'en': 'Add Product to Store',
      'de': 'Produkt zum Shop hinzufügen',
      'zh': '将商品添加到店铺',
      'ru': 'Добавить товар в магазин',
      'fr': 'Ajouter le produit à la boutique',
    },
    'enter_name_ar_error': {
      'ar': 'من فضلك أدخل الاسم بالعربية',
      'en': 'Please enter Arabic name',
      'de': 'Bitte geben Sie den arabischen Namen ein',
      'zh': '请输入阿拉伯语名称',
      'ru': 'Пожалуйста, введите название на арабском',
      'fr': 'Veuillez saisir le nom en arabe',
    },
    'enter_name_en_error': {
      'ar': 'من فضلك أدخل الاسم بالإنجليزية',
      'en': 'Please enter English name',
      'de': 'Bitte geben Sie den englischen Namen ein',
      'zh': '请输入英语名称',
      'ru': 'Пожалуйста, введите название на английском',
      'fr': 'Veuillez saisir le nom en anglais',
    },
    'enter_price_error': {
      'ar': 'من فضلك أدخل السعر',
      'en': 'Please enter price',
      'de': 'Bitte geben Sie den Preis ein',
      'zh': '请输入价格',
      'ru': 'Пожалуйста, введите цену',
      'fr': 'Veuillez saisir le prix',
    },
    'invalid_price_error': {
      'ar': 'السعر غير صحيح',
      'en': 'Invalid price',
      'de': 'Ungültiger Preis',
      'zh': '价格无效',
      'ru': 'Неверная цена',
      'fr': 'Prix invalide',
    },
    'product_added_success': {
      'ar': 'تمت إضافة المنتج بنجاح! 🎉',
      'en': 'Product added successfully! 🎉',
      'de': 'Produkt erfolgreich hinzugefügt! 🎉',
      'zh': '商品添加成功！🎉',
      'ru': 'Товар успешно добавлен! 🎉',
      'fr': 'Produit ajouté avec succès ! 🎉',
    },
    // SellerRegisterScreen
    'store_name': {
      'ar': 'اسم المتجر',
      'en': 'Store Name',
      'de': 'Geschäftsname',
      'zh': '店铺名称',
      'ru': 'Название магазина',
      'fr': 'Nom de la boutique',
    },
    'business_category_label': {
      'ar': 'نوع النشاط (مثال: ملابس، خضروات)',
      'en': 'Business Category (e.g., Fashion, Grocery)',
      'de': 'Geschäftskategorie (z.B. Mode, Lebensmittel)',
      'zh': '经营类别（例如：服装、杂货）',
      'ru': 'Категория бизнеса (например: Одежда, Продукты)',
      'fr': 'Catégorie d\'activité (ex: Mode, Épicerie)',
    },
    'store_email': {
      'ar': 'البريد الإلكتروني للمتجر',
      'en': 'Store Email Address',
      'de': 'E-Mail-Adresse des Geschäfts',
      'zh': '店铺电子邮件',
      'ru': 'Email магазина',
      'fr': 'Adresse e-mail de la boutique',
    },
    'store_phone': {
      'ar': 'رقم هاتف المتجر',
      'en': 'Store Phone Number',
      'de': 'Telefonnummer des Geschäfts',
      'zh': '店铺电话号码',
      'ru': 'Номер телефона магазина',
      'fr': 'Numéro de téléphone de la boutique',
    },
    'store_address': {
      'ar': 'عنوان المتجر بالتفصيل',
      'en': 'Detailed Store Address',
      'de': 'Detaillierte Geschäftsadresse',
      'zh': '详细店铺地址',
      'ru': 'Подробный адрес магазина',
      'fr': 'Adresse de boutique détaillée',
    },
    'create_seller_account': {
      'ar': 'إنشاء حساب بائع',
      'en': 'Create Seller Account',
      'de': 'Verkäuferkonto erstellen',
      'zh': '创建商家账号',
      'ru': 'Создать аккаунт продавца',
      'fr': 'Créer un compte vendeur',
    },
    'enter_store_name': {
      'ar': 'من فضلك أدخل اسم المتجر',
      'en': 'Please enter store name',
      'de': 'Bitte geben Sie den Geschäftsnamen ein',
      'zh': '请输入店铺名称',
      'ru': 'Пожалуйста, введите название магазина',
      'fr': 'Veuillez saisir le nom de la boutique',
    },
    'enter_business_cat': {
      'ar': 'من فضلك أدخل نوع النشاط',
      'en': 'Please enter activity type',
      'de': 'Bitte geben Sie die Aktivitätsart ein',
      'zh': '请输入经营类别',
      'ru': 'Пожалуйста, введите тип деятельности',
      'fr': 'Veuillez saisir le type d\'activité',
    },
    'enter_store_email': {
      'ar': 'من فضلك أدخل البريد الإلكتروني للمتجر',
      'en': 'Please enter email address',
      'de': 'Bitte geben Sie die E-Mail ein',
      'zh': '请输入电子邮件地址',
      'ru': 'Пожалуйста, введите email',
      'fr': 'Veuillez saisir l\'adresse e-mail',
    },
    'enter_store_address': {
      'ar': 'من فضلك أدخل العنوان',
      'en': 'Please enter store address',
      'de': 'Bitte geben Sie die Geschäftsadresse ein',
      'zh': '请输入店铺地址',
      'ru': 'Пожалуйста, введите адрес магазина',
      'fr': 'Veuillez saisir l\'adresse de la boutique',
    },
    'seller_registered_success': {
      'ar': 'تم التسجيل كبائع بنجاح! 🎉',
      'en': 'Successfully registered as a seller! 🎉',
      'de': 'Erfolgreich als Verkäufer registriert! 🎉',
      'zh': '成功注册为商家！🎉',
      'ru': 'Вы успешно зарегистрированы как продавец! 🎉',
      'fr': 'Inscription en tant que vendeur réussie ! 🎉',
    },
    // SellerDashboard
    'my_products_tab': {
      'ar': 'منتجاتي',
      'en': 'My Products',
      'de': 'Meine Produkte',
      'zh': '我的商品',
      'ru': 'Мои товары',
      'fr': 'Mes produits',
    },
    'received_orders_tab': {
      'ar': 'الطلبات الواردة',
      'en': 'Received Orders',
      'de': 'Erhaltene Bestellungen',
      'zh': '收到的订单',
      'ru': 'Полученные заказы',
      'fr': 'Commandes reçues',
    },
    'my_store': {
      'ar': 'متجري',
      'en': 'My Store',
      'de': 'Mein Shop',
      'zh': '我的店铺',
      'ru': 'Мой магазин',
      'fr': 'Ma boutique',
    },
    'activity_label': {
      'ar': 'النشاط:',
      'en': 'Activity:',
      'de': 'Aktivität:',
      'zh': '经营类别：',
      'ru': 'Деятельность:',
      'fr': 'Activité :',
    },
    'add_product_btn_label': {
      'ar': 'إضافة منتج',
      'en': 'Add Product',
      'de': 'Produkt hinzufügen',
      'zh': '添加商品',
      'ru': 'Добавить товар',
      'fr': 'Ajouter un produit',
    },
    'total_sales': {
      'ar': 'إجمالي المبيعات',
      'en': 'Total Sales',
      'de': 'Gesamtumsatz',
      'zh': '总销售额',
      'ru': 'Общие продажи',
      'fr': 'Ventes totales',
    },
    'my_products_list': {
      'ar': 'قائمة منتجاتي',
      'en': 'My Products List',
      'de': 'Meine Produktliste',
      'zh': '我的商品列表',
      'ru': 'Список моих товаров',
      'fr': 'Liste de mes produits',
    },
    'active_status': {
      'ar': 'نشط',
      'en': 'Active',
      'de': 'Aktiv',
      'zh': '活跃',
      'ru': 'Активен',
      'fr': 'Actif',
    },
    'no_received_orders': {
      'ar': 'لا توجد طلبات واردة حالياً!',
      'en': 'No received orders yet!',
      'de': 'Noch keine Bestellungen erhalten!',
      'zh': '暂无收到的订单！',
      'ru': 'Полученных заказов пока нет!',
      'fr': 'Aucune commande reçue pour le moment !',
    },
    // DeliveryRegister
    'delivery_register_title': {
      'ar': 'التسجيل كمندوب توصيل',
      'en': 'Register as Delivery Driver',
      'de': 'Als Zusteller registrieren',
      'zh': '注册为配送员',
      'ru': 'Регистрация курьера',
      'fr': 'S\'enregistrer comme livreur',
    },
    'driver_name': {
      'ar': 'اسم المندوب بالكامل',
      'en': 'Full Name',
      'de': 'Vollständiger Name',
      'zh': '配送员姓名',
      'ru': 'Полное имя курьера',
      'fr': 'Nom complet du livreur',
    },
    'driver_email': {
      'ar': 'البريد الإلكتروني للمندوب',
      'en': 'Driver Email Address',
      'de': 'Zusteller-E-Mail-Adresse',
      'zh': '配送员电子邮件',
      'ru': 'Email курьера',
      'fr': 'Adresse e-mail du livreur',
    },
    'driver_phone': {
      'ar': 'رقم الهاتف للمندوب',
      'en': 'Driver Phone Number',
      'de': 'Zusteller-Telefonnummer',
      'zh': '配送员电话号码',
      'ru': 'Номер телефона курьера',
      'fr': 'Numéro de téléphone du livreur',
    },
    'vehicle_type': {
      'ar': 'نوع وسيلة الانتقال (مثال: دراجة نارية، سيارة)',
      'en': 'Vehicle Type (e.g., Motorcycle, Car)',
      'de': 'Fahrzeugtyp (z.B. Motorrad, Auto)',
      'zh': '交通工具（例如：摩托车、汽车）',
      'ru': 'Тип транспорта (например: Мотоцикл, Машина)',
      'fr': 'Type de véhicule (ex : Moto, Voiture)',
    },
    'license_plate': {
      'ar': 'رقم لوحة المركبة (اختياري)',
      'en': 'License Plate Number (Optional)',
      'de': 'Kennzeichen (Optional)',
      'zh': '车牌号（可选）',
      'ru': 'Номерной знак (необязательно)',
      'fr': 'Plaque d\'immatriculation (optionnel)',
    },
    'create_driver_account': {
      'ar': 'إنشاء حساب مندوب',
      'en': 'Create Driver Account',
      'de': 'Fahrerkonto erstellen',
      'zh': '创建配送员账号',
      'ru': 'Создать аккаунт курьера',
      'fr': 'Créer un compte livreur',
    },
    'enter_driver_name': {
      'ar': 'من فضلك أدخل الاسم بالكامل',
      'en': 'Please enter full name',
      'de': 'Bitte geben Sie Ihren vollständigen Namen ein',
      'zh': '请输入您的姓名',
      'ru': 'Пожалуйста, введите полное имя',
      'fr': 'Veuillez saisir votre nom complet',
    },
    'enter_vehicle_type': {
      'ar': 'من فضلك أدخل نوع وسيلة الانتقال',
      'en': 'Please enter vehicle type',
      'de': 'Bitte geben Sie den Fahrzeugtyp ein',
      'zh': '请输入交通工具类型',
      'ru': 'Пожалуйста, введите тип транспорта',
      'fr': 'Veuillez saisir le type de véhicule',
    },
    'driver_registered_success': {
      'ar': 'تم التسجيل كمندوب توصيل بنجاح! 🎉',
      'en': 'Successfully registered as a delivery driver! 🎉',
      'de': 'Erfolgreich als Zusteller registriert! 🎉',
      'zh': '配送员注册成功！🎉',
      'ru': 'Вы успешно зарегистрированы как курьер! 🎉',
      'fr': 'Inscription en tant que livreur réussie ! 🎉',
    },
    // DeliveryDashboard
    'available_orders': {
      'ar': 'طلبات متاحة للتوصيل',
      'en': 'Available Orders',
      'de': 'Verfügbare Bestellungen',
      'zh': '可接订单',
      'ru': 'Доступные заказы',
      'fr': 'Commandes disponibles',
    },
    'my_active_orders': {
      'ar': 'طلباتي الحالية',
      'en': 'My Active Orders',
      'de': 'Meine aktiven Bestellungen',
      'zh': '我的当前订单',
      'ru': 'Мои активные заказы',
      'fr': 'Mes commandes actives',
    },
    'driver_label': {
      'ar': 'المندوب:',
      'en': 'Driver:',
      'de': 'Fahrer:',
      'zh': '配送员：',
      'ru': 'Курьер:',
      'fr': 'Livreur :',
    },
    'vehicle_label': {
      'ar': 'المركبة:',
      'en': 'Vehicle:',
      'de': 'Fahrzeug:',
      'zh': '交通工具：',
      'ru': 'Транспорт:',
      'fr': 'Véhicule :',
    },
    'deliver_to': {
      'ar': 'توصيل إلى:',
      'en': 'Deliver to:',
      'de': 'Liefern an:',
      'zh': '派送到：',
      'ru': 'Доставить в:',
      'fr': 'Livrer à :',
    },
    'customer_phone': {
      'ar': 'رقم العميل:',
      'en': 'Customer Phone:',
      'de': 'Kunden-Telefonnummer:',
      'zh': '客户电话：',
      'ru': 'Телефон клиента:',
      'fr': 'Tél client :',
    },
    'accept_delivery': {
      'ar': 'قبول التوصيل',
      'en': 'Accept Delivery',
      'de': 'Lieferung akzeptieren',
      'zh': '接受配送',
      'ru': 'Принять заказ',
      'fr': 'Accepter la livraison',
    },
    'mark_delivered': {
      'ar': 'تم التوصيل للعميل',
      'en': 'Mark as Delivered',
      'de': 'Als geliefert markieren',
      'zh': '标记为已送达',
      'ru': 'Отметить как доставленный',
      'fr': 'Marquer comme livré',
    },
    'no_available_orders': {
      'ar': 'لا توجد طلبات متاحة حالياً!',
      'en': 'No available orders at the moment!',
      'de': 'Zur Zeit keine Bestellungen verfügbar!',
      'zh': '当前暂无可接订单！',
      'ru': 'На данный момент нет доступных заказов!',
      'fr': 'Aucune commande disponible pour le moment !',
    },
    'no_active_orders': {
      'ar': 'لا توجد لديك طلبات جارية حالياً!',
      'en': 'No active orders currently!',
      'de': 'Aktuell keine aktiven Bestellungen!',
      'zh': '当前没有进行中的订单！',
      'ru': 'У вас сейчас нет активных заказов!',
      'fr': 'Vous n\'avez pas de commande active en ce moment !',
    },
    'order_accepted_success': {
      'ar': 'تم قبول الطلب وجاري التوصيل! 🚗',
      'en': 'Order accepted, delivering now! 🚗',
      'de': 'Bestellung akzeptiert, Lieferung läuft! 🚗',
      'zh': '订单已接受，正在配送！🚗',
      'ru': 'Заказ принят, доставляется! 🚗',
      'fr': 'Commande acceptée, livraison en cours ! 🚗',
    },
    'delivery_completed_success': {
      'ar': 'تم إكمال التوصيل بنجاح! 🎉',
      'en': 'Delivery completed successfully! 🎉',
      'de': 'Lieferung erfolgreich abgeschlossen! 🎉',
      'zh': '配送成功！🎉',
      'ru': 'Доставка успешно завершена! 🎉',
      'fr': 'Livraison effectuée avec succès ! 🎉',
    },
  };

  // Translations for default product names on-the-fly
  static const Map<String, Map<String, String>> _productTranslations = {
    'Fresh Tomatoes 1KG': {
      'ar': 'طماطم طازجة 1 كيلو',
      'en': 'Fresh Tomatoes 1KG',
      'de': 'Frische Tomaten 1 kg',
      'zh': '新鲜西红柿 1公斤',
      'ru': 'Свежие помидоры 1 кг',
      'fr': 'Tomates fraîches 1 kg',
    },
    'Fresh Cucumber 1KG': {
      'ar': 'خيار بلدي 1 كيلو',
      'en': 'Fresh Cucumber 1KG',
      'de': 'Frische Gurken 1 kg',
      'zh': '新鲜黄瓜 1公斤',
      'ru': 'Свежие огурцы 1 кг',
      'fr': 'Concombres frais 1 kg',
    },
    'Comfortable Cotton Boxers (Pack of 5)': {
      'ar': 'بوكسر قطن مريح (طقم 5 قطع)',
      'en': 'Comfortable Cotton Boxers (Pack of 5)',
      'de': 'Bequeme Baumwollboxershorts (5er-Pack)',
      'zh': '舒适纯棉平角裤（5件装）',
      'ru': 'Удобные хлопковые боксеры (5 шт.)',
      'fr': 'Caleçons confortables en coton (lot de 5)',
    },
    'Casual Cotton T-Shirt': {
      'ar': 'تيشرت قطن كاجوال',
      'en': 'Casual Cotton T-Shirt',
      'de': 'Casual Baumwoll-T-Shirt',
      'zh': '休闲纯棉T恤',
      'ru': 'Повседневная хлопковая футболка',
      'fr': 'T-shirt décontracté en coton',
    },
    'Comfortable Sneakers': {
      'ar': 'حذاء رياضي مريح',
      'en': 'Comfortable Sneakers',
      'de': 'Bequeme Sneaker',
      'zh': '舒适运动鞋',
      'ru': 'Удобные кроссовки',
      'fr': 'Baskets confortables',
    },
    'Wireless Computer Mouse': {
      'ar': 'ماوس كمبيوتر لاسلكي',
      'en': 'Wireless Computer Mouse',
      'de': 'Kabellose Computer-Maus',
      'zh': '无线电脑鼠标',
      'ru': 'Беспроводная компьютерная мышь',
      'fr': 'Souris d\'ordinateur sans fil',
    },
    'Mechanical Keyboard': {
      'ar': 'لوحة مفاتيح ميكانيكية',
      'en': 'Mechanical Keyboard',
      'de': 'Mechanische Tastatur',
      'zh': '机械键盘',
      'ru': 'Механическая клавиатура',
      'fr': 'Clavier mécanique',
    },
    'Gaming Headset': {
      'ar': 'سماعة رأس محيطية',
      'en': 'Gaming Headset',
      'de': 'Gaming-Headset',
      'zh': '游戏耳机',
      'ru': 'Игровая гарнитура',
      'fr': 'Casque de jeu',
    },
    'Fast Charger 20W': {
      'ar': 'شاحن سريع 20 وات',
      'en': 'Fast Charger 20W',
      'de': '20W Schnellladegerät',
      'zh': '20W 快速充电器',
      'ru': 'Быстрое зарядное устройство 20 Вт',
      'fr': 'Chargeur rapide 20W',
    },
    'Sunflower Oil 1L': {
      'ar': 'زيت عباد الشمس 1 لتر',
      'en': 'Sunflower Oil 1L',
      'de': 'Sonnenblumenöl 1 l',
      'zh': '葵花籽油 1升',
      'ru': 'Подсолнечное масло 1 л',
      'fr': 'Huile de tournesol 1L',
    },
    'Premium Egyptian Rice 5KG': {
      'ar': 'أرز مصري فاخر 5 كيلو',
      'en': 'Premium Egyptian Rice 5KG',
      'de': 'Premium ägyptischer Reis 5 kg',
      'zh': '优质埃及大米 5公斤',
      'ru': 'Египетский рис премиум-класса 5 кг',
      'fr': 'Riz égyptien de qualité supérieure 5 kg',
    },
    'Chocolate Croissant': {
      'ar': 'كرواسون شوكولاتة',
      'en': 'Chocolate Croissant',
      'de': 'Schokoladencroissant',
      'zh': '巧克力牛角包',
      'ru': 'Шоколадный круассан',
      'fr': 'Croissant au chocolat',
    },
    'White Toast Bread': {
      'ar': 'خبز توست أبيض',
      'en': 'White Toast Bread',
      'de': 'Weißbrot-Toast',
      'zh': '白吐司面包',
      'ru': 'Белый тостовый хлеб',
      'fr': 'Pain de mie blanc',
    },
  };

  static String get(String key, String lang) {
    if (_translations.containsKey(key)) {
      return _translations[key]![lang] ?? _translations[key]!['en'] ?? key;
    }
    return key;
  }

  static String translateProduct(String nameAr, String nameEn, String lang) {
    // If it's one of default products, translate it fully
    if (_productTranslations.containsKey(nameEn)) {
      return _productTranslations[nameEn]![lang] ?? _productTranslations[nameEn]!['en'] ?? nameEn;
    }
    // For other custom user products, fallback to NameAr for 'ar' or NameEn for others
    if (lang == 'ar') {
      return nameAr.isNotEmpty ? nameAr : nameEn;
    }
    return nameEn.isNotEmpty ? nameEn : nameAr;
  }

  static String translateCategory(String categoryEn, String lang) {
    final Map<String, Map<String, String>> cats = {
      'All': {
        'ar': 'الكل',
        'en': 'All',
        'de': 'Alle',
        'zh': '全部',
        'ru': 'Все',
        'fr': 'Tout',
      },
      'Vegetables': {
        'ar': 'خضروات',
        'en': 'Vegetables',
        'de': 'Gemüse',
        'zh': '蔬菜',
        'ru': 'Овощи',
        'fr': 'Légumes',
      },
      'Fashion': {
        'ar': 'ملابس',
        'en': 'Fashion',
        'de': 'Mode',
        'zh': '时尚',
        'ru': 'Одежда',
        'fr': 'Mode',
      },
      'Computers': {
        'ar': 'كمبيوتر',
        'en': 'Computers',
        'de': 'Computer',
        'zh': '电脑',
        'ru': 'Компьютеры',
        'fr': 'Ordinateurs',
      },
      'Electronics': {
        'ar': 'إلكترونيات',
        'en': 'Electronics',
        'de': 'Elektronik',
        'zh': '电子产品',
        'ru': 'Электроника',
        'fr': 'Électronique',
      },
      'Grocery': {
        'ar': 'بقالة',
        'en': 'Grocery',
        'de': 'Lebensmittel',
        'zh': '杂货',
        'ru': 'Бакалея',
        'fr': 'Épicerie',
      },
      'Bakery': {
        'ar': 'مخبوزات',
        'en': 'Bakery',
        'de': 'Bäckerei',
        'zh': '烘焙',
        'ru': 'Выпечка',
        'fr': 'Boulangerie',
      },
    };
    if (cats.containsKey(categoryEn)) {
      return cats[categoryEn]![lang] ?? cats[categoryEn]!['en'] ?? categoryEn;
    }
    return categoryEn;
  }
}
